
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef AGGUIDEIM_H
#define AGGUIDEIM_H

#include "nxtype.h"
extern UNS8 TINavEn;//农机具联合导航功能开关,0：关闭，1:开启
extern UNS16 GpsPrecisionIm;//农具定位精度
extern REAL64 Gps_XIm;		/* 农具GNSS坐标 ecef m */
extern REAL64 Gps_YIm;		/* 农具GNSS坐标 ecef m */
extern REAL64 Gps_ZIm;		/* 农具GNSS坐标 ecef m*/
extern INTEGER16 VTGHeadingIm;		/* 农具GNSS Vtg航向  0.01rad */
extern UNS16 Gps_HDOPIm;		/* 农具GNSS*/
extern INTEGER32 Gps_EllipseHeightIm;		/* 农具GNSS*/
extern UNS8 SatellitesIm;		/* 农具GNSS卫星颗数*/
extern UNS8 FixStateIm;         /* 农具GNSS定位状态*/
extern INTEGER16 RollIm;		/* 农具实时横滚角, 0.01degree*/
extern INTEGER16 PitchIm;		/* 农具实时俯仰角, 0.01degree*/
extern UNS16 UpdateDTIm;		/* 农具实时数据算法周期, ms*/
extern UNS8 ImplementType;      //1:三点悬挂，2：单点悬挂，3：对行农具
extern INTEGER16 LeverArmXIm;		/* 农具小盘天线到农具中轴中心距离，左正右负*/  // mm
extern INTEGER16 LeverArmYIm;		/* 农具小盘天线到农具后轴距离，后正前负*/  // cm
extern INTEGER16 LeverArmZIm;		/* 农具小盘天线到地面距离，负*/  // cm
extern INTEGER16 LeverTRT;		/* 车辆后轴中心到农具挂载点距离，正*/  // cm
extern INTEGER16 LeverTIR;		/* 农具挂载点到农具后轴中心距离，正*/  // cm
extern INTEGER16 LeverRH;		/* 农具后轴中线到地面高度，正*/  // cm
extern INTEGER16 RollOffsetIm;   /*农具IMU安装误差--横滚角偏差*/  // 0.01degree
extern INTEGER16 PitchOffsetIm;  /*农具IMU安装误差--俯仰角偏差*/  // 0.01degree
extern UNS8 AllAttitudeIm;       /*农具IMU全姿态安装*/
extern UNS8 HeadingSwapIm;      /*农具航向取反*/
extern UNS8 bReverseIm;		/*农具前进倒车状态*/
extern INTEGER16 XTrackIm;		/*农具横向偏差*/  // cm
extern INTEGER16 XHeadingIm;		/*农具航向偏差*/  // 0.01degree
extern UNS8 CalibrateCmdIm;    /*农具IMU安装误差标定指令*/
extern UNS16 CalibratePhaseIm;		/*农具IMU安装误差标定状态*/
extern UNS8 CalibrationCheckIm;		// 1 = 只有副天线异常， 2 =  只有tc 异常， 3 = 两个都异常   /*农具IMU安装误差标核验码*/ //
extern INTEGER32 LongitudeIm;		/* Mapped at index 0x2020, subindex 0x00*/   // 软件定线用，cm
extern INTEGER32 LatitudeIm;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS16 GPSHeadingIm;		/* Mapped at index 0x2023, subindex 0x00*/  // 0.01degree
extern UNS16 IntegralSwitchIm;  // 农具积分，
/*农具导航场景参数，和拖拉机导航一一对应，精度相同*/
extern UNS16 GainSteeringIm;
extern UNS16 GainxTrackIm;
extern UNS16 GainxHeadingIm;
extern UNS16 GainRIm;
extern UNS16 GainLearnIm;
extern UNS16 PTimeIm;
extern UNS16 PTimeOffIm;
extern INTEGER16 OnlineAggresivenessIm;
extern INTEGER16 ApproachAggresivenessIm;
extern UNS8 ImpControlMode;   // 对应拖拉机最大转角，精度相同
extern UNS8 UserLineType;  // 用户定线的线类型，同一条导航线该值不会变: AB，A+ = 1；圆曲线=2；曲线=3；调头曲线/边界曲线/路径线=4；耙地线=5


#endif // AGGUIDE_H
